from playwright.sync_api import Playwright, expect, Page
from pytest_playwright.pytest_playwright import browser

from Playwright.utils.web_API import APIutils


def test_e2e_web_api(playwright: Playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()


    # Create order and grab order ID
    utils = APIutils()
    orderID = utils.create_order(playwright)


    # Login
    page.goto("https://rahulshettyacademy.com/client")
    page.get_by_placeholder("email@example.com").fill("anshika@gmail.com")
    page.get_by_placeholder("enter your passsword").fill("Iamking@000")
    page.get_by_role("button", name="Login").click()


    # Order page and verify order ID
    page.get_by_role("button", name="ORDERS").click()
    row = page.locator("tr").filter(has_text=orderID)
    row.get_by_role("button", name="View").click()
    expect(page.locator("//div/p[@class='tagline']")).to_contain_text("Thank you for Shopping With Us")
    context.close()
    page.close()


# Mocking of API is also called as Intercepting the API network
# API call from browser -> API contacts server and return response back to browser -> Browser use this response to generate HTML of page
# Verifying the zero state message displayed on ORDERS page when no orders present, without deleting the orders on page, using fake API response
fake_orders_response = {"data": [], "message": "No Orders"}

def intercept_response(route):
    route.fulfill(                              # fulfill() method is used to fulfill the response fo the route with fake response to intercept
        json=fake_orders_response,
    )


def test_mocking_api(playwright: Playwright, page: Page):
    page.goto("https://rahulshettyacademy.com/client")
    page.route("https://rahulshettyacademy.com/api/ecom/order/get-orders-for-customer/*", intercept_response)         # * indicates the regular expression, means till / everything is constant and after / there changing value, so we indicate that value using *
                                                                                                                            # route() method is used to pass the base URL and what fake response need to pass it, that response should be function
    page.get_by_placeholder("email@example.com").fill("anshika@gmail.com")
    page.get_by_placeholder("enter your passsword").fill("Iamking@000")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="ORDERS").click()

    # Verifying the zero state message displayed on ORDERS page when no orders present, without deleting the orders on page, using fake API response
    zero_case_message = page.locator(".mt-4").text_content().strip()
    print(zero_case_message)
    assert zero_case_message == "You have No Orders to show at this time. Please Visit Back Us"


# Test to save and inject the session cookie at browser during runtime with playwright
# When any API is called, then token is being created (inspect page, go to Application > Local Storage)
# Open new tab, inspect page, go to Application > Local Storage add above token and hitl the URL, credentials required for logic will be bypass
def test_session_token_storage(playwright: Playwright):
    utils = APIutils()
    login_token = utils.get_login_token(playwright)
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page= context.new_page()

    # Inject token in session local storage
    page.add_init_script(f"""localStorage.setItem('token', '{login_token}')""")        # add_init_script() requires JS as arg and should be """ """
                                                                                       # For the .setItem() method key is 'token' here which is acceptable in browser and called ad local storage key, verify by inspecting and creating one token manually, that same key we need to pass here
                                                                                       # This JS will add the login_token generated by get_login_token method and pass in local story of the session, so that no login credential will be required to login and go to Orders page
    page.goto("https://rahulshettyacademy.com/client")
    page.get_by_role("button", name="ORDERS").click()
    expect(page.get_by_text("Your Orders")).to_be_visible()
    page.close()
    browser.close()



